Write a NumPy program to multiply two given arrays of same size element-by-
element
.

In [1]:
import numpy as np
print("Please write the elements of the array in a single line and separated by a space: ")   
elements = list(map(int, input().split()))    
matrix1 = np.array(elements)
print(matrix1)  
print("Please write the elements of the matrix in a single line and separated by a space: ")  
elements = list(map(int, input().split()))   
matrix2 = np.array(elements)
print(matrix2)
matrix = matrix1 * matrix2
print(matrix1*matrix2)

Please write the elements of the array in a single line and separated by a space: 


 1 3 5 7 9


[1 3 5 7 9]
Please write the elements of the matrix in a single line and separated by a space: 


 1 3 5 7 9


[1 3 5 7 9]
[ 1  9 25 49 81]


Write a NumPy program to find the missing data in a given array.

In [2]:
elements = ([1,3,5,np.nan])
nums=np.array(elements)
print("Original array:")
print(nums)
print("\nFind the missing data of the said array:")
ans=np.isnan(nums)
print(ans)
print("Data is missing in index: ")
for i in range(len(ans)):
    if ans[i] == True:
       print(i)

Original array:
[ 1.  3.  5. nan]

Find the missing data of the said array:
[False False False  True]
Data is missing in index: 
3


Write a NumPy program to test whether each element of a 1-D array is also present in
a second array.

In [3]:
elements1=list(map(int,input().split()))
matrix1=np.array(elements1)
elements2=list(map(int,input().split()))
matrix2=np.array(elements2)
ans = np.isin(matrix1,matrix2)
print(ans)

 1 3 5 7 9
 9 5 7 3 1


[ True  True  True  True  True]


Write a NumPy program to save a NumPy array to a text file.

In [4]:
new_data = np.array([[2, 4, 6],
                     [8, 10, 12],
                     [14, 16, 18]])
new_file_path = 'new_output.txt'
np.savetxt(new_file_path, new_data, fmt='%d', delimiter=',')
print(f"New NumPy array saved to {new_file_path}")

New NumPy array saved to new_output.txt


Write a NumPy program to save a NumPy array to a text file.

In [5]:
import numpy as np
x = np.linspace(2.5, 6.5, 30)
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


Write a Pandas program to convert Series of lists to one Series.

In [6]:
import pandas as pd

new_data = {'Text': ['python', 'java', 'javascript', 'csharp', 'ruby']}
new_series = pd.Series(new_data['Text'])

new_word_lengths = new_series.str.len()

print("New Original Series:")
print(new_series)
print("\nNumber of characters in each word:")
print(new_word_lengths)

New Original Series:
0        python
1          java
2    javascript
3        csharp
4          ruby
dtype: object

Number of characters in each word:
0     6
1     4
2    10
3     6
4     4
dtype: int64


Write a Pandas program to convert Series of lists to one Series.

In [7]:
import pandas as pd
new_series_of_lists = pd.Series([[10, 20, 30, 40], [50, 60], [70, 80, 90]])
new_result_series = new_series_of_lists.explode()
print("New Original Series:")
print(new_series_of_lists)
print("\nNew Converted Series:")
print(new_result_series)

New Original Series:
0    [10, 20, 30, 40]
1            [50, 60]
2        [70, 80, 90]
dtype: object

New Converted Series:
0    10
0    20
0    30
0    40
1    50
1    60
2    70
2    80
2    90
dtype: object


Write a Pandas program to create a subset of a given series based on value and
condition.

In [8]:
new_data = {'X': 15, 'Y': 25, 'Z': 35, 'W': 45, 'K': 55}
new_series = pd.Series(new_data)
new_condition = new_series <= 25
new_subset_series = new_series[new_condition]
print("New Original Series:")
print(new_series)
print("\nNew Subset Series based on new condition:")
print(new_subset_series)

New Original Series:
X    15
Y    25
Z    35
W    45
K    55
dtype: int64

New Subset Series based on new condition:
X    15
Y    25
dtype: int64


Write a Pandas program to display most frequent value in a given series and replace
everything else as "Other" in the series.

In [9]:
new_data = {'Category': ['X', 'Y', 'X', 'Z', 'Y', 'X', 'X', 'Z', 'Z']}
new_series = pd.Series(new_data['Category'])
new_most_frequent_value = new_series.mode()[0]
new_modified_series = new_series.where(new_series == new_most_frequent_value, 'Other')
print("New Original Series:")
print(new_series)
print("\nNew Modified Series:")
print(new_modified_series)

New Original Series:
0    X
1    Y
2    X
3    Z
4    Y
5    X
6    X
7    Z
8    Z
dtype: object

New Modified Series:
0        X
1    Other
2        X
3    Other
4    Other
5        X
6        X
7    Other
8    Other
dtype: object


Write a Pandas program to find the positions of numbers that are multiples of 5 of a
given series.

In [10]:
new_data = {'Numbers': [8, 12, 18, 22, 25, 32, 40, 45]}
new_series = pd.Series(new_data['Numbers'])
new_positions_of_multiples_of_5 = new_series.index[new_series % 5 == 0]
print("New Original Series:")
print(new_series)
print("\nNew Positions of numbers that are multiples of 5:")
print(new_positions_of_multiples_of_5)

New Original Series:
0     8
1    12
2    18
3    22
4    25
5    32
6    40
7    45
dtype: int64

New Positions of numbers that are multiples of 5:
Index([4, 6, 7], dtype='int64')


Write a Pandas program to calculate the number of characters in each word in a given
series.

In [11]:
new_data = {'Text': ['python', 'java', 'javascript', 'csharp', 'ruby']}
new_series = pd.Series(new_data['Text'])
new_word_lengths = new_series.str.len()
print("New Original Series:")
print(new_series)
print("\nNumber of characters in each word:")
print(new_word_lengths)

New Original Series:
0        python
1          java
2    javascript
3        csharp
4          ruby
dtype: object

Number of characters in each word:
0     6
1     4
2    10
3     6
4     4
dtype: int64


Write a Pandas program to convert year-month string to dates adding a specified day
of the month.

In [12]:
new_data = {'YearMonth': ['2023-05', '2023-06', '2023-07', '2023-08']}
new_series = pd.Series(new_data['YearMonth'])
new_day_of_month = 10
new_result_dates = pd.to_datetime(new_series + '-' + str(new_day_of_month), format='%Y-%m-%d')
print("New Original Series:")
print(new_series)
print("\nNew Resulting Dates:")
print(new_result_dates)

New Original Series:
0    2023-05
1    2023-06
2    2023-07
3    2023-08
dtype: object

New Resulting Dates:
0   2023-05-10
1   2023-06-10
2   2023-07-10
3   2023-08-10
dtype: datetime64[ns]


Write a Pandas program to create and display a DataFrame from a specified
dictionary data which has the index labels.

In [13]:
data = {'Name': ['akshay', 'cherry', 'akash', 'abhay'],
        'Age': [25, 30, 22, 28],
        'City': ['New York', 'Los Angeles', 'Chicago', 'San Francisco']}
index_labels = ['Person1', 'Person2', 'Person3', 'Person4']
df = pd.DataFrame(data, index=index_labels)
print(df)

           Name  Age           City
Person1  akshay   25       New York
Person2  cherry   30    Los Angeles
Person3   akash   22        Chicago
Person4   abhay   28  San Francisco


Write a Pandas program to select the rows where the number of attempts in the
examination is greater than 2.

In [14]:
new_data = {'Name': ['Cherry', 'akshay', 'abhay', 'Akash', 'abhi'],
            'Attempts': [4, 5, 2, 3, 4],
            'Score': [89, 95, 70, 85, 92]}
new_df = pd.DataFrame(new_data)
new_result_df = new_df[new_df['Attempts'] > 2]
print("New DataFrame:")
print(new_df)
print("\nSelected rows where the number of attempts is greater than 2:")
print(new_result_df)

New DataFrame:
     Name  Attempts  Score
0  Cherry         4     89
1  akshay         5     95
2   abhay         2     70
3   Akash         3     85
4    abhi         4     92

Selected rows where the number of attempts is greater than 2:
     Name  Attempts  Score
0  Cherry         4     89
1  akshay         5     95
3   Akash         3     85
4    abhi         4     92


Write a Pandas program to append a new row "k" to data frame with given values for
each column. Now delete the new row and return the original DataFrame.

In [15]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['akshay','cherry','chinni','joy','abhay'],
        'score': [12.5, 9, 16.5, np.nan, 9],
        'attempts': [1, 3, 2, 3, 2],
        'qualify': ['yes', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e']
df = pd.DataFrame(exam_data , index=labels)
print("Original rows:")
print(df)
print("nAppend a new row:")
df.loc['k'] = [1, 'Suresh', 'yes', 15.5]
print("Print all records after insert a new record:")
print(df)
print("nDelete the new row and display the original  rows:")
df = df.drop('k')
print(df)

Original rows:
     name  score  attempts qualify
a  akshay   12.5         1     yes
b  cherry    9.0         3      no
c  chinni   16.5         2     yes
d     joy    NaN         3      no
e   abhay    9.0         2      no
nAppend a new row:
Print all records after insert a new record:
     name   score attempts qualify
a  akshay    12.5        1     yes
b  cherry     9.0        3      no
c  chinni    16.5        2     yes
d     joy     NaN        3      no
e   abhay     9.0        2      no
k       1  Suresh      yes    15.5
nDelete the new row and display the original  rows:
     name score attempts qualify
a  akshay  12.5        1     yes
b  cherry   9.0        3      no
c  chinni  16.5        2     yes
d     joy   NaN        3      no
e   abhay   9.0        2      no


Write a Pandas program to sort the DataFrame first by "name" in descending order,
then by "score" in ascending order.

In [16]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['akshay', 'tanish', 'dedipya', 'abhay', 'avinash'],
        'score': [12.5, 9, 16.5, np.nan, 9],
        'attempts': [1, 3, 2, 3, 2],
        'qualify': ['yes', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e']
df = pd.DataFrame(exam_data , index=labels)
print("Orginal rows:")
print(df)
df = df.sort_values(by=['name', 'score'], ascending=[False, True])
print("Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:")
print(df)

Orginal rows:
      name  score  attempts qualify
a   akshay   12.5         1     yes
b   tanish    9.0         3      no
c  dedipya   16.5         2     yes
d    abhay    NaN         3      no
e  avinash    9.0         2      no
Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:
      name  score  attempts qualify
b   tanish    9.0         3      no
c  dedipya   16.5         2     yes
e  avinash    9.0         2      no
a   akshay   12.5         1     yes
d    abhay    NaN         3      no


Write a Pandas program to replace the &#39;qualify&#39; column contains the values "yes" and
"no" with True and False

In [17]:
new_data = {'Name': ['akshay', 'cherry', 'akash', 'abhi'],
            'Attempts': [2, 3, 1, 4],
            'Qualify': ['yes', 'no', 'yes', 'no']}
new_df = pd.DataFrame(new_data)
print("New DataFrame:")
print(new_df)
new_df['Qualify'] = new_df['Qualify'].replace({'yes': True, 'no': False})
print("\nNew DataFrame after replacing 'yes' and 'no' with True and False:")
print(new_df)

New DataFrame:
     Name  Attempts Qualify
0  akshay         2     yes
1  cherry         3      no
2   akash         1     yes
3    abhi         4      no

New DataFrame after replacing 'yes' and 'no' with True and False:
     Name  Attempts  Qualify
0  akshay         2     True
1  cherry         3    False
2   akash         1     True
3    abhi         4    False


Write a Pandas program to remove infinite values from a given DataFrame.

In [18]:
import pandas as pd
import numpy as np

new_data = {'A': [3, 6, np.inf, 9],
            'B': [np.inf, 11, 13, 15]}

new_df = pd.DataFrame(new_data)

print("New DataFrame:")
print(new_df)

new_df.replace([np.inf, -np.inf], np.nan, inplace=True)

new_df = new_df.dropna()

print("\nNew DataFrame after removing infinite values:")
print(new_df)

New DataFrame:
     A     B
0  3.0   inf
1  6.0  11.0
2  inf  13.0
3  9.0  15.0

New DataFrame after removing infinite values:
     A     B
1  6.0  11.0
3  9.0  15.0
